spring:
  application:
    name: Project2
  datasource:
    url: jdbc:postgresql://localhost:5432/violation
    username: admin
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: springboot-app
            client-secret: olbyY0IWGJ5QTEIxG4EgjzaocEw3UFrS
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: http://localhost:9098/realms/violation-system
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9098/realms/violation-system

server:
  port: 8888